export const ApplicationConstants = {
  DEFAULT_UNBLOCK_INTERVAL_IN_MINS: 5,
  SUCCESS_STR: 'Success',
  ERROR_STR: 'Error',
  PROFILE_IMAGE_VERSION: '_1',
  PROFILE_IMAGE_FOLDER: 'profile_image/',
  STRING: 'string',
  OBJECT_STR: 'object',
  MESSAGE_STR: 'message',
  ALPHABETS_REGEX: "^[A-Za-z\\s'-]+$",
  ALPHANUMERICS_REGEX: "^[A-Za-z0-9\\s'-]+$",
  SEPARATOR_SYMBOL: ':-',
  CODE_STR: 'code',
  PROD_ENVIRONMENT_KEY: 'prod',
  DEV_ENVIRONMENT_KEY: 'dev',
  EntityType: { DEPARTMENT: 'department', USER_ROLE: 'userrole' },
  PROFILE_IMAGE_BUCKET: 'profile_image',
  PROFILE_IMAGE_MIME: 'image',
  TRUE: 'true',
  FALSE: 'false',
  GROUPBY_USERS: ['userRole', 'userGroup', 'isActive', 'orgId'],
  COMMENT_MAX_LENGTH: 100,
  DEFAULT_ORG_ID: '11111111-1111-1111-11111111111111111',
  SITE_ADDRESS_MAX_LENGTH: 300,
  COUNTRY_CODES: ['IN'],
  IS_ACTIVE_KEY: 'isActive',
  STRAPI_PROJECT_DOCUMENT: 'project-documents',
  STRAPI_PROJECT_LOGO: 'project-logos',
  STRAPI_PROJECT_ID: 'projectId',
  STRAPI_ORG_ID: 'orgId',
  GROUPBY_ENTITIES_USERS: ['userRole', 'userGroup', 'department', 'orgId'],
  UNIT_TYPES: [
    '1RK',
    '1BHK',
    '1.5BHK',
    '2BHK',
    '2.5BHK',
    '3BHK',
    '3.5BHK',
    '4BHK',
  ],
};
